// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ8MzeKpGZY9wdsXmKMoHXYSt_xhOIZ6c',
    appId: '1:649676226025:web:492cd90c0a59b567779f78',
    messagingSenderId: '649676226025',
    projectId: 'insta-clone-a5210',
    authDomain: 'insta-clone-a5210.firebaseapp.com',
    storageBucket: 'insta-clone-a5210.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvpWYBvoNSBnIr051SrRTY-GbUE848Zd8',
    appId: '1:649676226025:android:a46732b9db2388f3779f78',
    messagingSenderId: '649676226025',
    projectId: 'insta-clone-a5210',
    storageBucket: 'insta-clone-a5210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEsdkYSHDOj2qa3kYAY1tUZEWQBoLQMM',
    appId: '1:649676226025:ios:925843ee22ac8799779f78',
    messagingSenderId: '649676226025',
    projectId: 'insta-clone-a5210',
    storageBucket: 'insta-clone-a5210.appspot.com',
    iosClientId: '649676226025-6p6p8ah10in2kba95qvev731ql92tup2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmEsdkYSHDOj2qa3kYAY1tUZEWQBoLQMM',
    appId: '1:649676226025:ios:b1fecef2df2ab7ff779f78',
    messagingSenderId: '649676226025',
    projectId: 'insta-clone-a5210',
    storageBucket: 'insta-clone-a5210.appspot.com',
    iosClientId: '649676226025-ook32scq0f04hovjvnh8tl3riqk9thie.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
